SinjulMSBH_Version21_Sample/Controllers/SinjulMSBHController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SinjulMSBH_Version21_Sample.Data;
using SinjulMSBH_Version21_Sample.Models.EntityFrameworkCore21;

namespace SinjulMSBH_Version21_Sample.Controllers
{
	public class SinjulMSBHController: Controller
	{
		private readonly ApplicationDbContext _context;

		public SinjulMSBHController ( ApplicationDbContext context )
		{
			_context = context;
		}

		public async Task<IActionResult> Index ( )
		{
			return View( await _context.Products.ToListAsync( ) );
		}

		// GET: SinjulMSBH
		public async Task<IActionResult> ProductListUsingTagHelpers ( )
		{
			return View( await _context.Products.ToListAsync( ) );

			//  .GroupBy( o => new { o.CustomerId , o.EmployeeId } )
			//  .Select( g => new
			//  {
			// 	 g.Key.CustomerId ,
			// 	 g.Key.EmployeeId ,
			// 	 Sum = g.Sum( o => o.Amount ) ,
			// 	 Min = g.Min( o => o.Amount ) ,
			// 	 Max = g.Max( o => o.Amount ) ,
			// 	 Avg = g.Average( o => Amount )
			//  } );
		}

		// GET: SinjulMSBH/Details/5
		public async Task<IActionResult> Details ( int? id )
		{
			if ( id == null )
			{
				return NotFound( );
			}

			var product = await _context.Products
		    .FirstOrDefaultAsync(m => m.Id == id);
			if ( product == null )
			{
				return NotFound( );
			}

			return View( product );
		}

		// GET: SinjulMSBH/Create
		public IActionResult Create ( )
		{
			return View( );
		}

		// POST: SinjulMSBH/Create
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create ( [Bind( "Id,ProductName,UnitPrice,Number,Description,HomePage" )] Product product )
		{
			if ( ModelState.IsValid )
			{
				_context.Add( product );
				await _context.SaveChangesAsync( );
				return RedirectToAction( nameof( Index ) );
			}
			return View( product );
		}

		// GET: SinjulMSBH/Edit/5
		public async Task<IActionResult> Edit ( int? id )
		{
			if ( id == null )
			{
				return NotFound( );
			}

			var product = await _context.Products.FindAsync(id);
			if ( product == null )
			{
				return NotFound( );
			}
			return View( product );
		}

		// POST: SinjulMSBH/Edit/5
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit ( int id , [Bind( "Id,ProductName,UnitPrice,Number,Description,HomePage" )] Product product )
		{
			if ( id != product.Id )
			{
				return NotFound( );
			}

			if ( ModelState.IsValid )
			{
				try
				{
					_context.Update( product );
					await _context.SaveChangesAsync( );
				}
				catch ( DbUpdateConcurrencyException )
				{
					if ( !ProductExists( product.Id ) )
					{
						return NotFound( );
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction( nameof( Index ) );
			}
			return View( product );
		}

		// GET: SinjulMSBH/Delete/5
		public async Task<IActionResult> Delete ( int? id )
		{
			if ( id == null )
			{
				return NotFound( );
			}

			var product = await _context.Products
		    .FirstOrDefaultAsync(m => m.Id == id);
			if ( product == null )
			{
				return NotFound( );
			}

			return View( product );
		}

		// POST: SinjulMSBH/Delete/5
		[HttpPost, ActionName( "Delete" )]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed ( int id )
		{
			var product = await _context.Products.FindAsync(id);
			_context.Products.Remove( product );
			await _context.SaveChangesAsync( );
			return RedirectToAction( nameof( Index ) );
		}

		private bool ProductExists ( int id )
		{
			return _context.Products.Any( e => e.Id == id );
		}
	}
}

SinjulMSBH_Version21_Sample/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SinjulMSBH_Version21_Sample.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

SinjulMSBH_Version21_Sample/Pages/Chat.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SinjulMSBH_Version21_Sample.Pages
{
	[Authorize]
	public class ChatModel: PageModel
	{
		public void OnGet ( )
		{
		}
	}
}

SinjulMSBH_Version21_Sample/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SinjulMSBH_Version21_Sample.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

SinjulMSBH_Version21_Sample/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SinjulMSBH_Version21_Sample.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

SinjulMSBH_Version21_Sample/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SinjulMSBH_Version21_Sample.Models.IntroducingHTTPClientFactory;

namespace SinjulMSBH_Version21_Sample.Pages
{
	public class IndexModel: PageModel
	{
		//https://msdnshared.blob.core.windows.net/media/2018/02/DiagnosticLogs.png
		//		An incoming request in to localhost:5001 in this case this is the browser navigating to my Razor Pages page.
		//MVC selecting a handler for the request , the OnGetAsync method of my PageModel.
		//The beginning of an outgoing HTTP request, this marks the start of the outgoing pipeline that we will discuss in the next section.
		//We send a HTTP request with the given verb.
		//Recieve the request back in 439.6606 ms, with a status of OK.
		//End the outgoing HTTP pipeline.
		//End and return from our handler.

		//If you set the LogLevel to at least Debug then we will also log header information. In the following screenshot I added an accept header to my request, and you can see the response headers:
		//https://msdnshared.blob.core.windows.net/media/2018/02/DebugLogs.png

		//public async Task OnGetAsync ( [FromServices]ValuesClient client )
		//{
		//	var values = await client.GetValues();
		//}

		//private ValuesClient _valuesClient;
		//private GitHubService _ghService;

		//private ValuesService _valuesService;

		public IndexModel ( /*ValuesClient valuesClient *//* GitHubService ghService*/ /*, ValuesService valuesService */)
		{
			//_valuesClient = valuesClient;
			//_ghService=ghService;
			//_valuesService=valuesService;
		}

		//public IEnumerable<string> Values;

		public async Task OnGetAsync ( )
		{
			//var valuesme = await _ghService.GetValues();
			//var result = await _ghService.Client.GetStringAsync("/orgs/octokit/repos");
			//Values = await _valuesClient.GetValues( );
		}
	}
}

SinjulMSBH_Version21_Sample/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SinjulMSBH_Version21_Sample.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

SinjulMSBH_Version21_Sample/Pages/About.cshtml
@page
@model AboutModel
@{
      ViewData[ "Title" ] = "About";
}
<h2>@ViewData[ "Title" ]</h2>
<h3>@Model.Message</h3>

<p>Use this area to provide additional information.</p>

SinjulMSBH_Version21_Sample/Pages/Chat.cshtml
@page
@model ChatModel
@{
      ViewData[ "Title" ] = "Chat";
}

<h1>Chat</h1>

<form id="send-form" action="#">
      Send a message:
      <input type="text" id="message-textbox" disabled />
      <button id="send-button" type="submit" disabled>Send</button>
</form>

<ul id="messages-list"></ul>

@section Scripts {
      <script src="~/lib/signalr/dist/browser/signalr.js"></script>
      <script type="text/javascript">
            // Bind DOM elements
            var sendForm = document.getElementById("send-form");
            var sendButton = document.getElementById("send-button");
            var messagesList = document.getElementById("messages-list");
            var messageTextBox = document.getElementById("message-textbox");

            function appendMessage(content) {
                  var li = document.createElement("li");
                  li.innerText = content;
                  messagesList.appendChild(li);
            }

            var connection = new signalR.HubConnection("/hubs/chat");

            sendForm.addEventListener("submit", function () {
                  var message = messageTextBox.value;
                  messageTextBox.value = "";
                  connection.send("Send", message);
            });

            connection.on("SendMessage", function (sender, message) {
                  appendMessage(sender + ': ' + message);
            });

            connection.on("SendAction", function (sender, action) {
                  appendMessage(sender + ' ' + action);
            });

            connection.start().then(function () {
                  messageTextBox.disabled = false;
                  sendButton.disabled = false;
            });
      </script>
}

SinjulMSBH_Version21_Sample/Pages/Contact.cshtml
@page
@model ContactModel
@{
      ViewData[ "Title" ] = "Contact";
}
<h2>@ViewData[ "Title" ]</h2>
<h3>@Model.Message</h3>

<h2>BTW, this is from a Class Library .. !!!!</h2>

<partial name="_Message" />

<address>
      One Microsoft Way<br />
      Redmond, WA 98052-6399<br />
      <abbr title="Phone">P:</abbr>
      425.555.0100
</address>

<address>
      <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
      <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SinjulMSBH_Version21_Sample/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core Razor Pages</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?linkid=852130">Working with Razor Pages.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure App Service</a></li>
        </ul>
    </div>
</div>

SinjulMSBH_Version21_Sample/Pages/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>@ViewData[ "Title" ] - SinjulMSBH_Version21_Sample</title>

      <environment include="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />
      </environment>
      <environment exclude="Development">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
      </environment>
</head>
<body>
      <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                  <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                              <span class="sr-only">Toggle navigation</span>
                              <span class="icon-bar"></span>
                              <span class="icon-bar"></span>
                              <span class="icon-bar"></span>
                        </button>
                        <a asp-page="/Index" class="navbar-brand">SinjulMSBH_Version21_Sample</a>
                  </div>
                  <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                              <li><a asp-page="/Index">Home</a></li>
                              <li><a asp-page="/About">About</a></li>
                              <li><a asp-page="/Contact">Contact</a></li>
                              <li><a asp-page="/Chat">Chat</a></li>
                              <li>
                                    <a asp-controller="SinjulMSBH" asp-action="ProductListUsingTagHelpers">
                                          ProductListUsingTagHelpers
                                    </a>
                              </li>
                        </ul>
                        @await Html.PartialAsync( "_LoginPartial" )
                  </div>
            </div>
      </nav>

      <partial name="_CookieConsentPartial" />

      <div class="container body-content">
            @RenderBody( )
            <hr />
            <footer>
                  <p>&copy; 1396 - SinjulMSBH_Version21_Sample</p>
            </footer>
      </div>

      <environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
      </environment>
      <environment exclude="Development">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
      </environment>

      @RenderSection( "Scripts" , required: false )
</body>
</html>